language: cpp
dist: trusty
addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - lcov
      - g++-7
      - boost1.67
      - libgtest-dev
compiler:
  - gcc
os:
  - linux
script:
  - export CXX=g++-7
  - export CC=gcc-7
  - mkdir build && cd build
  - mkdir install
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install
  - cmake --build . --target install
  - ./test/MyLibraryTests