language: cpp
dist: trusty
addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-7
      - python3-pip
compiler:
  - gcc
install:
  - sudo pip3 install virtualenv
  - mkdir env
  - virtualenv env
  - source env/bin/activate
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3.4 get-pip.py
  - sudo pip install conan
os:
  - linux
script:
  - export CXX=g++-7
  - export CC=gcc-7
  - mkdir build && cd build
  - mkdir install
  - conan install ..
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install
  - cmake --build . --target install
  - ctest -VV